services:
  postgres:
    image: postgres:16.3
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=median-db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
    command: >
      sh -c "npx prisma migrate deploy && npm run start:prod"

  seed:
    build: .
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
    entrypoint: ["sh", "-c", "npx prisma migrate deploy && npx prisma db seed"]

volumes:
  postgres:
